Added proxy support
givip/Telegrammer pull request #38
Opened 2020-01-07 14:30 UTC by Ferrerohub

2020-01-07 14:43 UTC, Ferrerohub commented
OMG, I'm using the [Ray Wenderlich's style recommendations](https://github.com/raywenderlich/swift-style-guide#correctness), but code doesn't look the same as here

2020-01-07 16:38 UTC, givip reviewed
Yes, you are right, code style is not as described by Ray Wenderlich. Have to fix CONTRIBUTING guide

2020-01-07 16:38 UTC, givip commented on Sources/Telegrammer/Network/Bot.Settings+Proxy.swift
> +    public static func server(host: String, port: Int) -> Proxy {
This method is redundant, its covered by following method

2020-01-07 16:38 UTC, givip commented on Sources/Telegrammer/Bot/Telegram/Bot.swift
> +        let proxy = settings.proxy.map(HTTPClient.Configuration.Proxy.init)
Interesting approach, looks like I missed this from Optional macOS 10.15 updates

2020-01-07 16:49 UTC, givip requested changes

2020-01-07 16:49 UTC, givip commented on Sources/Telegrammer/Bot/Telegram/Bot.swift
> +        public var proxy: Bot.Settings.Proxy? = nil
no `nil` needed

2020-01-07 16:49 UTC, givip commented on Sources/Telegrammer/Network/Bot.Settings+Proxy.swift
> +public extension Bot.Settings {
Please make 4 spaces everywhere

2020-01-07 16:49 UTC, givip commented on Sources/Telegrammer/Network/BotClient.swift
> +				worker: HTTPClient.EventLoopGroupProvider,
spaces instead tabs

2020-01-08 17:38 UTC, givip approved these changes

2020-01-08 17:38 UTC, merged